insert into Product (ProductName, Price) values ('Ham - Black Forest', 88.97);
insert into Product (ProductName, Price) values ('Tea - Darjeeling, Azzura', 54.69);
insert into Product (ProductName, Price) values ('Skirt - 29 Foot', 66.23);
insert into Product (ProductName, Price) values ('Rappini - Andy Boy', 64.6);
insert into Product (ProductName, Price) values ('Beer - Moosehead', 96.08);
insert into Product (ProductName, Price) values ('Pork - Loin, Center Cut', 60.49);
insert into Product (ProductName, Price) values ('Vinegar - White Wine', 71.4);
insert into Product (ProductName, Price) values ('Water Chestnut - Canned', 51.04);
insert into Product (ProductName, Price) values ('Pork - Hock And Feet Attached', 97.16);
insert into Product (ProductName, Price) values ('Okra', 95.85);
insert into Product (ProductName, Price) values ('Spice - Greek 1 Step', 29.35);
insert into Product (ProductName, Price) values ('Doilies - 12, Paper', 93.83);
insert into Product (ProductName, Price) values ('Celery', 87.06);
insert into Product (ProductName, Price) values ('Water - Green Tea Refresher', 57.54);
insert into Product (ProductName, Price) values ('Longos - Cheese Tortellini', 49.88);
insert into Product (ProductName, Price) values ('Milk - Buttermilk', 41.86);
insert into Product (ProductName, Price) values ('Nut - Pumpkin Seeds', 57.94);
insert into Product (ProductName, Price) values ('Cheese - Brie', 58.39);
insert into Product (ProductName, Price) values ('Tofu - Soft', 67.81);
insert into Product (ProductName, Price) values ('Juice - Cranberry, 341 Ml', 2.18);
insert into Product (ProductName, Price) values ('Water - Evian 355 Ml', 39.7);
insert into Product (ProductName, Price) values ('Celery', 15.6);
insert into Product (ProductName, Price) values ('Garlic', 55.95);
insert into Product (ProductName, Price) values ('Soup - Campbells Pasta Fagioli', 46.51);
insert into Product (ProductName, Price) values ('Pork Salted Bellies', 80.61);
insert into Product (ProductName, Price) values ('Flour - So Mix Cake White', 98.4);
insert into Product (ProductName, Price) values ('Capers - Ox Eye Daisy', 35.43);
insert into Product (ProductName, Price) values ('Appetizer - Veg Assortment', 32.27);
insert into Product (ProductName, Price) values ('Beef Tenderloin Aaa', 79.65);
insert into Product (ProductName, Price) values ('Bonito Flakes - Toku Katsuo', 38.74);
insert into Product (ProductName, Price) values ('Chocolate - Dark', 3.83);
insert into Product (ProductName, Price) values ('Creme De Banane - Marie', 82.1);
insert into Product (ProductName, Price) values ('Wine - Domaine Boyar Royal', 16.68);
insert into Product (ProductName, Price) values ('Straws - Cocktale', 7.08);
insert into Product (ProductName, Price) values ('Soup - Knorr, Veg / Beef', 20.65);
insert into Product (ProductName, Price) values ('Oats Large Flake', 18.74);
insert into Product (ProductName, Price) values ('Pear - Halves', 13.59);
insert into Product (ProductName, Price) values ('Pepper - Cubanelle', 64.23);
insert into Product (ProductName, Price) values ('Wine - Red, Gallo, Merlot', 15.14);
insert into Product (ProductName, Price) values ('Lemonade - Strawberry, 591 Ml', 56.72);
insert into Product (ProductName, Price) values ('Coffee - Dark Roast', 86.65);
insert into Product (ProductName, Price) values ('Pasta - Cannelloni, Sheets, Fresh', 46.48);
insert into Product (ProductName, Price) values ('Pasta - Rotini, Colour, Dry', 94.28);
insert into Product (ProductName, Price) values ('Salt - Table', 35.38);
insert into Product (ProductName, Price) values ('Cheese - Swiss Sliced', 96.04);
insert into Product (ProductName, Price) values ('Sobe - Cranberry Grapefruit', 27.67);
insert into Product (ProductName, Price) values ('Soup - Cream Of Broccoli, Dry', 61.44);
insert into Product (ProductName, Price) values ('Raspberries - Frozen', 6.81);
insert into Product (ProductName, Price) values ('Pork - Ham, Virginia', 1.12);
insert into Product (ProductName, Price) values ('Juice - Orange', 45.47);
insert into Product (ProductName, Price) values ('Rice - Aborio', 35.02);
insert into Product (ProductName, Price) values ('Godiva White Chocolate', 50.83);
insert into Product (ProductName, Price) values ('Gingerale - Schweppes, 355 Ml', 87.14);
insert into Product (ProductName, Price) values ('Tart Shells - Sweet, 2', 59.72);
insert into Product (ProductName, Price) values ('Beef - Texas Style Burger', 42.61);
insert into Product (ProductName, Price) values ('Milk - Homo', 10.8);
insert into Product (ProductName, Price) values ('Jam - Apricot', 3.18);
insert into Product (ProductName, Price) values ('Pepper - Roasted Red', 87.25);
insert into Product (ProductName, Price) values ('Stock - Veal, Brown', 20.35);
insert into Product (ProductName, Price) values ('Cabbage - Green', 48.14);
insert into Product (ProductName, Price) values ('Dasheen', 98.8);
insert into Product (ProductName, Price) values ('Maintenance Removal Charge', 66.12);
insert into Product (ProductName, Price) values ('Soup - Beef Conomme, Dry', 53.68);
insert into Product (ProductName, Price) values ('Truffle Cups - Red', 20.96);
insert into Product (ProductName, Price) values ('Juice - Ocean Spray Kiwi', 86.54);
insert into Product (ProductName, Price) values ('Cheese - Bakers Cream Cheese', 57.01);
insert into Product (ProductName, Price) values ('Wine - Red, Concha Y Toro', 88.37);
insert into Product (ProductName, Price) values ('Cactus Pads', 48.04);
insert into Product (ProductName, Price) values ('Juice - Prune', 18.85);
insert into Product (ProductName, Price) values ('Pork - Side Ribs', 24.16);
insert into Product (ProductName, Price) values ('Pork - Liver', 27.84);
insert into Product (ProductName, Price) values ('Soup - Tomato Mush. Florentine', 37.47);
insert into Product (ProductName, Price) values ('Wine - Merlot Vina Carmen', 1.25);
insert into Product (ProductName, Price) values ('Wine - Chateau Timberlay', 65.86);
insert into Product (ProductName, Price) values ('Wine - Red, Gallo, Merlot', 44.57);
insert into Product (ProductName, Price) values ('Pear - Halves', 2.15);
insert into Product (ProductName, Price) values ('Ice Cream Bar - Oreo Sandwich', 28.34);
insert into Product (ProductName, Price) values ('Mushroom - Shitake, Fresh', 98.22);
insert into Product (ProductName, Price) values ('Swiss Chard', 66.83);
insert into Product (ProductName, Price) values ('Pepper Squash', 85.82);
insert into Product (ProductName, Price) values ('Garam Marsala', 80.57);
insert into Product (ProductName, Price) values ('Roe - Flying Fish', 83.29);
insert into Product (ProductName, Price) values ('Pork - Tenderloin, Frozen', 38.34);
insert into Product (ProductName, Price) values ('Squid - U - 10 Thailand', 76.56);
insert into Product (ProductName, Price) values ('Pasta - Canelloni', 59.72);
insert into Product (ProductName, Price) values ('Capon - Breast, Double, Wing On', 56.46);
insert into Product (ProductName, Price) values ('Chick Peas - Canned', 58.86);
insert into Product (ProductName, Price) values ('Syrup - Kahlua Chocolate', 93.0);
insert into Product (ProductName, Price) values ('Ecolab Crystal Fusion', 5.65);
insert into Product (ProductName, Price) values ('Roe - Lump Fish, Black', 54.12);
insert into Product (ProductName, Price) values ('Lobster - Base', 71.34);
insert into Product (ProductName, Price) values ('Ice - Clear, 300 Lb For Carving', 6.38);
insert into Product (ProductName, Price) values ('Beer - Muskoka Cream Ale', 62.32);
insert into Product (ProductName, Price) values ('Glass Clear 8 Oz', 9.85);
insert into Product (ProductName, Price) values ('Frangelico', 52.61);
insert into Product (ProductName, Price) values ('Dill Weed - Dry', 69.94);
insert into Product (ProductName, Price) values ('Garbage Bags - Black', 35.1);
insert into Product (ProductName, Price) values ('Red Currants', 83.17);
insert into Product (ProductName, Price) values ('Wine - Sake', 73.5);
insert into Product (ProductName, Price) values ('Scallops - 20/30', 33.42);
